apiVersion: v1
name: sso-requests
version: 0.0.2
appVersion: 5.0.2
description: CSS Application for requesting integrations
dependencies:
  - name: patroni
    version: 1.6.1
    repository: https://bcgov.github.io/sso-helm-charts
  - name: redis
    version: 21.1.7
    repository: https://charts.bitnami.com/bitnami
  - name: backup-storage
    version: 0.1.16
    repository: https://bcgov.github.io/helm-charts
